import express from 'express';
import { verifyAdmin, verifyToken } from '../middleware/auth.js';
import { supabaseAdmin } from '../config/supabase.js';

const router = express.Router();

// Create new booking
router.post('/', verifyToken, async (req, res) => {
  try {
    const { userId, serviceType, serviceId, serviceName, date, time, notes, price } = req.body;

    const { data: booking, error } = await supabaseAdmin
      .from('bookings')
      .insert([
        {
          user_id: userId,
          service_type: serviceType,
          service_id: serviceId,
          service_name: serviceName,
          booking_date: date,
          booking_time: time,
          notes: notes || '',
          price: price,
          status: 'pending',
          created_at: new Date().toISOString()
          // invoice_number and encrypted_code will be auto-generated by trigger
        }
      ])
      .select()
      .single();

    if (error) throw error;

    res.status(201).json({
      success: true,
      message: 'تم إنشاء الحجز بنجاح',
      booking
    });
  } catch (error) {
    console.error('Create booking error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء إنشاء الحجز'
    });
  }
});

// Get user bookings
router.get('/user/:userId', verifyToken, async (req, res) => {
  try {
    const { userId } = req.params;

    const { data: bookings, error } = await supabaseAdmin
      .from('bookings')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) throw error;

    res.json({
      success: true,
      bookings
    });
  } catch (error) {
    console.error('Get user bookings error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء جلب الحجوزات'
    });
  }
});

// Get all bookings (Admin only)
router.get('/', verifyAdmin, async (req, res) => {
  try {
    const { page = 1, limit = 10, status = '', serviceType = '' } = req.query;
    const offset = (page - 1) * limit;

    let query = supabaseAdmin
      .from('bookings')
      .select(`
        *,
        users:user_id (
          id,
          name,
          email,
          phone
        )
      `, { count: 'exact' });

    if (status) {
      query = query.eq('status', status);
    }

    if (serviceType) {
      query = query.eq('service_type', serviceType);
    }

    const { data: bookings, error, count } = await query
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (error) throw error;

    res.json({
      success: true,
      bookings,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total: count,
        totalPages: Math.ceil(count / limit)
      }
    });
  } catch (error) {
    console.error('Get bookings error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء جلب الحجوزات'
    });
  }
});

// Update booking status (Admin only)
router.patch('/:bookingId/status', verifyAdmin, async (req, res) => {
  try {
    const { bookingId } = req.params;
    const { status } = req.body;

    const { data: booking, error } = await supabaseAdmin
      .from('bookings')
      .update({
        status,
        updated_at: new Date().toISOString()
      })
      .eq('id', bookingId)
      .select(`
        *,
        users:user_id (
          id,
          name,
          email,
          phone
        )
      `)
      .single();

    if (error) throw error;

    res.json({
      success: true,
      message: 'تم تحديث حالة الحجز بنجاح',
      booking
    });
  } catch (error) {
    console.error('Update booking status error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء تحديث حالة الحجز'
    });
  }
});

// Accept booking (Admin only)
router.post('/:bookingId/accept', verifyAdmin, async (req, res) => {
  try {
    const { bookingId } = req.params;

    const { data: booking, error } = await supabaseAdmin
      .from('bookings')
      .update({
        status: 'confirmed',
        updated_at: new Date().toISOString()
      })
      .eq('id', bookingId)
      .select(`
        *,
        users:user_id (
          id,
          name,
          email,
          phone
        )
      `)
      .single();

    if (error) throw error;

    res.json({
      success: true,
      message: 'تم قبول الحجز بنجاح',
      booking
    });
  } catch (error) {
    console.error('Accept booking error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء قبول الحجز'
    });
  }
});

// Reject booking (Admin only)
router.post('/:bookingId/reject', verifyAdmin, async (req, res) => {
  try {
    const { bookingId } = req.params;

    const { data: booking, error } = await supabaseAdmin
      .from('bookings')
      .update({
        status: 'rejected',
        updated_at: new Date().toISOString()
      })
      .eq('id', bookingId)
      .select(`
        *,
        users:user_id (
          id,
          name,
          email,
          phone
        )
      `)
      .single();

    if (error) throw error;

    res.json({
      success: true,
      message: 'تم رفض الحجز',
      booking
    });
  } catch (error) {
    console.error('Reject booking error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء رفض الحجز'
    });
  }
});

// Delete booking (Admin only)
router.delete('/:bookingId', verifyAdmin, async (req, res) => {
  try {
    const { bookingId } = req.params;

    const { error } = await supabaseAdmin
      .from('bookings')
      .delete()
      .eq('id', bookingId);

    if (error) throw error;

    res.json({
      success: true,
      message: 'تم حذف الحجز بنجاح'
    });
  } catch (error) {
    console.error('Delete booking error:', error);
    res.status(500).json({
      error: true,
      message: 'حدث خطأ أثناء الحذف'
    });
  }
});

export default router;

